vim.keymap.set("n", "<leader>gs", vim.cmd.Git)
vim.keymap.set("n", "<leader>oo", "<CMD>Oil<CR>")
vim.keymap.set("n", "<leader>ot", "<CMD>tab Oil<CR>")
vim.keymap.set("n", "<leader>ov", "<CMD>vert Oil<CR>")
vim.keymap.set("n", "<leader>oh", "<CMD>belowright Oil<CR>")
vim.keymap.set("n", "<leader>u", vim.cmd.UndotreeToggle)
vim.keymap.set("n", "<leader>ff", "<CMD>Telescope find_files<CR>")
vim.keymap.set("n", "<leader>fg", "<CMD>Telescope live_grep<CR>")
vim.keymap.set("n", "<leader>i", function()
		vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled({ 0 }), { 0 })
end)
vim.keymap.set("n", "<leader>fd", function()
		require("telescope.builtin").diagnostics({ severity_limit = "Error" })
end)
vim.keymap.set("n", "<leader>fD", "<CMD>Telescope diagnostics<CR>")
vim.keymap.set("n", "<leader>d", function()
		vim.diagnostic.setqflist({ open = true, severity = vim.diagnostic.severity.ERROR })
end)
vim.keymap.set("n", "<leader>D", function()
		vim.diagnostic.setqflist({ open = true })
end)
vim.keymap.set("i", "jk", "<esc>l")
vim.keymap.set("n", "<leader>gd", vim.lsp.buf.definition, {})
vim.keymap.set("n", "<leader>fm", function()
		require("conform").format({ async = true })
end)
vim.keymap.set("n", "<c-d>", "<c-d>zz")
vim.keymap.set("n", "<c-u>", "<c-u>zz")
vim.keymap.set("n", "<leader>vrc", "<CMD>tabe ~/.config/cvim<CR>")
vim.keymap.set({ "n", "v" }, "<leader>y", '"+y')
vim.keymap.set("n", "<leader>yef", "<CMD>!cat % | pbcopy<CR>")

vim.keymap.set("n", "<leader>H", "<CMD>diffget //2<CR>")
vim.keymap.set("n", "<leader>L", "<CMD>diffget //3<CR>")
